-- Local development data: five bookings for every booking status.

-- Replace only this file's fixtures so the seed can be run repeatedly.
delete from public.booking_feedback
where booking_id in (
  select id from public.bookings where booking_number like 'SEED-%'
);

delete from public.payments
where booking_id in (
  select id from public.bookings where booking_number like 'SEED-%'
);

delete from public.bookings
where booking_number like 'SEED-%';

insert into auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
)
select
  '00000000-0000-0000-0000-000000000000'::uuid,
  seed.id,
  'authenticated',
  'authenticated',
  seed.email,
  crypt('seed-password-123', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  jsonb_build_object('full_name', seed.first_name || ' ' || seed.last_name),
  now(),
  now()
from (
  values
    ('10000000-0000-0000-0000-000000000001'::uuid, 'seed.customer.1@example.com', 'Maya', 'Santos'),
    ('10000000-0000-0000-0000-000000000002'::uuid, 'seed.customer.2@example.com', 'Luis', 'Reyes'),
    ('10000000-0000-0000-0000-000000000003'::uuid, 'seed.customer.3@example.com', 'Ana', 'Garcia'),
    ('10000000-0000-0000-0000-000000000004'::uuid, 'seed.customer.4@example.com', 'Noel', 'Cruz'),
    ('10000000-0000-0000-0000-000000000005'::uuid, 'seed.customer.5@example.com', 'Bea', 'Dela Cruz')
) as seed(id, email, first_name, last_name)
where not exists (select 1 from auth.users where auth.users.id = seed.id);

update public.profiles
set role = 'customer', is_active = true
where id in (
  '10000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000002',
  '10000000-0000-0000-0000-000000000003',
  '10000000-0000-0000-0000-000000000004',
  '10000000-0000-0000-0000-000000000005'
);

insert into public.vehicles (
  id,
  name,
  slug,
  plate_number,
  description,
  passenger_count,
  bag_count,
  transmission,
  fuel_type,
  base_price_per_day,
  driver_rate_per_day,
  km_per_liter,
  peso_per_km,
  security_deposit,
  security_deposit_type,
  is_available
)
values (
  '20000000-0000-0000-0000-000000000001',
  'Seed Commuter Deluxe',
  'seed-commuter-deluxe',
  'SEED-0001',
  'Development seed vehicle',
  7,
  4,
  'Automatic',
  'Diesel',
  4500,
  1500,
  10,
  0,
  1000,
  'fixed',
  true
)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  plate_number = excluded.plate_number,
  description = excluded.description,
  passenger_count = excluded.passenger_count,
  bag_count = excluded.bag_count,
  transmission = excluded.transmission,
  fuel_type = excluded.fuel_type,
  base_price_per_day = excluded.base_price_per_day,
  driver_rate_per_day = excluded.driver_rate_per_day,
  km_per_liter = excluded.km_per_liter,
  peso_per_km = excluded.peso_per_km,
  security_deposit = excluded.security_deposit,
  security_deposit_type = excluded.security_deposit_type,
  is_available = excluded.is_available;

with statuses(status, status_order) as (
  values
    ('for_review'::public.booking_status, 1),
    ('awaiting_documents'::public.booking_status, 2),
    ('pending_price_approval'::public.booking_status, 3),
    ('confirmed'::public.booking_status, 4),
    ('rejected'::public.booking_status, 5),
    ('canceled'::public.booking_status, 6),
    ('on_trip'::public.booking_status, 7),
    ('completed'::public.booking_status, 8)
),
seed_bookings as (
  select
    statuses.status,
    statuses.status_order,
    slots.slot,
    row_number() over (order by statuses.status_order, slots.slot) as sequence_number
  from statuses
  cross join generate_series(1, 5) as slots(slot)
)
insert into public.bookings (
  booking_number,
  customer_id,
  guest_name,
  guest_email,
  guest_mobile,
  vehicle_id,
  rental_model,
  booking_mode,
  status,
  start_at,
  end_at,
  duration_days,
  pickup_location,
  dropoff_location,
  destination,
  purpose_of_travel,
  notes,
  in_service_area
)
select
  format('SEED-%s-%s', upper(replace(seed.status::text, '_', '-')), lpad(seed.slot::text, 2, '0')),
  customer.id,
  concat(customer.first_name, ' ', customer.last_name),
  customer.email,
  format('+63 917 555 %s', lpad(seed.slot::text, 4, '0')),
  '20000000-0000-0000-0000-000000000001',
  'all_out',
  'keep',
  seed.status,
  timestamptz '2026-09-01 09:00:00+00' + (seed.sequence_number - 1) * interval '2 days',
  timestamptz '2026-09-02 09:00:00+00' + (seed.sequence_number - 1) * interval '2 days',
  1,
  'Villamor, Pasay City',
  'Makati City',
  'Metro Manila',
  'Development seed booking',
  'Generated by supabase/seed.sql',
  true
from seed_bookings as seed
join public.profiles as customer
  on customer.id = format('10000000-0000-0000-0000-00000000000%s', seed.slot)::uuid;

insert into public.payments (
  booking_id,
  channel,
  status,
  amount,
  reference_number,
  paid_at,
  submitted_by
)
select
  booking.id,
  'bank_transfer',
  (case
    when booking.status in ('rejected', 'canceled') then 'refunded'
    else 'submitted'
  end)::public.payment_status,
  booking.deposit_amount,
  format('SEED-DEPOSIT-%s', booking.booking_number),
  case when booking.status in ('for_review', 'awaiting_documents', 'pending_price_approval', 'confirmed', 'on_trip') then null else now() end,
  booking.customer_id
from public.bookings as booking
where booking.booking_number like 'SEED-%';

insert into public.payments (
  booking_id,
  channel,
  status,
  amount,
  reference_number,
  paid_at,
  submitted_by
)
select
  booking.id,
  'cash',
  'submitted',
  booking.total_amount - booking.deposit_amount,
  format('SEED-BALANCE-%s', booking.booking_number),
  now(),
  booking.customer_id
from public.bookings as booking
where booking.status = 'completed'
  and booking.booking_number like 'SEED-%';

insert into public.booking_feedback (
  booking_id,
  customer_id,
  vehicle_id,
  rating,
  feedback,
  status,
  display_on_homepage
)
select
  booking.id,
  booking.customer_id,
  booking.vehicle_id,
  case slot.slot
    when 1 then 5
    when 2 then 5
    when 3 then 4
    when 4 then 5
    else 4
  end,
  case slot.slot
    when 1 then 'The van was clean, comfortable, and ready on time.'
    when 2 then 'Smooth booking process and a very helpful team.'
    when 3 then 'Great vehicle for our group trip around Metro Manila.'
    when 4 then 'Everything was organized and easy from pickup to return.'
    else 'Reliable service and a comfortable ride.'
  end,
  'approved_testimonial',
  slot.slot <= 3
from public.bookings as booking
cross join lateral (
  select substring(booking.booking_number from '([0-9]{2})$')::integer as slot
) as slot
where booking.status = 'completed'
  and booking.booking_number like 'SEED-COMPLETED-%'
on conflict (booking_id) do nothing;
